---
- name: Create Admin User
  hosts: "{{ _hosts | default('os_windows') }}"
  vars:
    iis_message: undef

  tasks:
    - name: Change password
      ansible.windows.win_user:
        name: "{{ user_name }}"
        password: "{{ user_password }}"
        groups:
         - Administrators
         - Remote Desktop Users
        state: present
