---
- name: Install 7Zip from MSI
  hosts: "{{ _hosts | default('windows') }}"
  gather_facts: false

  tasks:
  - name: Create registry path MyCompany
    win_regedit:
      path: HKCU:\Software\MyCompany

  - name: Add or update registry path MyCompany, with entry 'hello', and containing 'world'
    win_regedit:
      path: HKCU:\Software\MyCompany
      name: hello
      data: world
