---
- name: Create a registry key
  hosts: "{{ _hosts | default('windows') }}"
  gather_facts: false

  tasks:
  - name: Create registry path MyCompany
    win_regedit:
      path: HKCU:\Software\MyCompany

  - name: Add or update registry path MyCompany
    win_regedit:
      path: HKCU:\Software\MyCompany
      name: "{{ reg_key }}"
      data: "{{ reg_value }}"
