---
- name: Create a registry key
  hosts: "{{ _hosts | default('windows') }}"
  gather_facts: false

  tasks:
  - name: Create registry path MyCompany
    ansible.windows.win_regedit:
      path: HKLM:\Software\MyCompany
      state: present

  - name: Add or update registry path MyCompany
    ansible.windows.win_regedit:
      path: HKLM:\Software\MyCompany
      name: "{{ reg_key }}"
      data: "{{ reg_value }}"
      state: present
